tokenauth_config_enable: true
tokenauth:
  items:
    - identifier: objects
      token: ba9d233e95e04c4a8a661a27daffe7c9bd019067
      contact_person: Person 1
      email: person-1@example.com
      organization: Organization 1
      application: Application 1
      administration: Administration 1
